In [1]:
## It is a technique used to encode categrorical values based on their relationship with the target variable
## This is useful when we have large number of unique categories

In [2]:
import pandas as pd
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 150, 300]
})

In [3]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    150
5     Paris    300

In [5]:
df.groupby('city')['price'].mean().to_dict()

{'London': 150.0, 'New York': 175.0, 'Paris': 300.0, 'Tokyo': 250.0}

In [6]:
df['city_encoded']=df['city'].map(df.groupby('city')['price'].mean().to_dict())

In [7]:
df['city_encoded']

0    175.0
1    150.0
2    300.0
3    250.0
4    175.0
5    300.0
Name: city_encoded, dtype: float64

In [8]:
df

       city  price  city_encoded
0  New York    200         175.0
1    London    150         150.0
2     Paris    300         300.0
3     Tokyo    250         250.0
4  New York    150         175.0
5     Paris    300         300.0

In [11]:
import seaborn as sns
data = sns.load_dataset('tips')

In [12]:
data['time_encoded']=data['time'].map(data.groupby('time')['total_bill'].mean().to_dict())

<ipython-input-12-0ce21def1842>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data['time_encoded']=data['time'].map(data.groupby('time')['total_bill'].mean().to_dict())

In [13]:
data['time_encoded']

0      20.797159
1      20.797159
2      20.797159
3      20.797159
4      20.797159
         ...
239    20.797159
240    20.797159
241    20.797159
242    20.797159
243    20.797159
Name: time_encoded, Length: 244, dtype: category
Categories (2, float64): [17.168676, 20.797159]